-- Two continuous aggregates that this file used to create, and 016 removes.
--
-- em_1m and em_1h, minute and hour rollups of em_sample, built so that a chart
-- covering a year would not read a year of one second rows. Nothing ever
-- queried them: the history page buckets em_sample directly and the longest
-- window it offers is 30 days. 016 drops them and keeps the raw rows for 400
-- days instead, which answers the same question from one table.
--
-- This file is emptied rather than left to create them, which is the one place
-- editing an applied migration is the right answer.
--
-- A database that has already run this file has "003_rollups.sql" in
-- schema_migration and will never read it again; the runner tracks names, not
-- checksums, so nothing installed anywhere is affected, and 016 removes what
-- this file made when it does run. A database created from now on skips
-- straight past it.
--
-- The reason it could not simply be left alone is that creating them and
-- dropping them seconds later is a race the migration runner loses. 003
-- registers a refresh policy, Timescale's scheduler picks the job up, and 016
-- drops the view out from under it:
--
--     asyncpg.exceptions.InternalServerError: tuple concurrently deleted
--
-- Unregistering the policy first, which 016 does, narrows the window and does
-- not close it: a job already running keeps running. It took CI out once and
-- then came back as one error in a suite of 450, because the test fixture
-- rebuilds the schema for every test and so runs this pair dozens of times. A
-- flaky migration is worse than a slow one; it teaches everybody to re-run the
-- suite rather than read it.
--
-- The name stays so the sequence is unbroken and the history is legible.

SELECT 1;
